# Generated by Django 5.2 on 2025-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Country Name'),
        ),
    ]
