# Generated by Django 5.2 on 2025-04-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_name_ar_city_name_he_country_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='State Name')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='State Code')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='locations.city', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'State',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
