# Generated by Django 5.2 on 2025-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='State Name'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='State Name'),
        ),
    ]
