# Generated by Django 5.2 on 2025-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_state_name_ar_state_name_he'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-create_at', '-update_at'), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('-create_at', '-update_at'), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='state',
            table=None,
        ),
    ]
