# Generated by Django 5.2 on 2025-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Shop Name'),
        ),
        migrations.AddField(
            model_name='agency',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Shop Name'),
        ),
        migrations.AddField(
            model_name='travel',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='travel',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='travel',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Travel Name'),
        ),
        migrations.AddField(
            model_name='travel',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Travel Name'),
        ),
    ]
