# Generated by Django 5.2 on 2025-04-05 17:44

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agency_name_ar_agency_name_he_travel_description_ar_and_more'),
        ('locations', '0004_state_name_ar_state_name_he'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='tag',
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='locations.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='locations.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='locations.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='agency',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='travel',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('hostel', 'Hostel'), ('camping', 'Camping'), ('guesthouse', 'Guesthouse'), ('resort', 'Resort'), ('1_star_hotel', '1 Star Hotel'), ('2_star_hotel', '2 Star Hotel'), ('3_star_hotel', '3 Star Hotel'), ('4_star_hotel', '4 Star Hotel'), ('5_star_hotel', '5 Star Hotel')], max_length=20, null=True, verbose_name='Housing Type'),
        ),
        migrations.AddField(
            model_name='travel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='agency.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='travel',
            name='travel_type',
            field=models.CharField(choices=[('single', 'Single'), ('couple', 'Couple'), ('family', 'Family'), ('group', 'Group')], max_length=20, null=True, verbose_name='Travel Type'),
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='Day')),
                ('is_close', models.BooleanField(default=False, help_text='Indicates whether the restaurant is close on this day', verbose_name='Close')),
                ('opening_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Closing Time')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='agency.agency', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Work Time',
                'verbose_name_plural': 'Work Times',
                'unique_together': {('agency', 'day')},
            },
        ),
    ]
