# Generated by Django 5.2 on 2025-04-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_remove_travel_duration_remove_travel_tag_agency_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('order', '-create_at', '-update_at'), 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
    ]
