# Generated by Django 5.2 on 2025-04-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_agency_options'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='info.theme', verbose_name='Theme'),
        ),
    ]
